
# Broadcast settings

broadcast:
  prefix: '&9WolfGalaxy >'

# Chat settings

chat:
  style: '%prefix% &f%name% %suffix% %allegiance% &8Â» &7%message%'
  channels:
    leadership:
      prefix: '&aLeadership &8|&7'
    higherstaff:
      prefix: '&6Higherstaff &8|&7'
    lowerstaff:
      prefix: '&eLowerstaff &8|&7'
    staff-general:
      prefix: '&bStaff General &8|&7'
    jedi:
      prefix: '&aJedi &8|&7'
    sith:
      prefix: '&4Sith &8|&7'
    global:
      prefix: '&eGlobal &8|&7'

# Messages

messages:
  curse: Do not swear!

# Discord settings

discord:
  token: MzQ3NTMxNjk2OTkzNzMwNTYw.DP9M7Q.kZWK_1qDPS3RxbFIDJULf2XZIrM
  channels:
    chat: 368718727367360512
    console: 374218865141481473
    announcements: 368135104293502997
    welcome: 367527668092239874
  messages:
    join: 'Welcome to **WolfGalaxyMC** {MENTION}! Have a great time here :wink: !'
    leave: 'Goodbye young padawan, may the force be with you!'

# Twitter settings

twitter:
  consumer_key: kZiJjixRnpLshTRjvuowo6rUX
  consumer_secret: TEEnCwikyp50CjLHVe4i0JnQgj8HkeEuUsBOMn8Fjj0FGy4ehp

